/* 
 * ARXivar Workflow API
 *
 * ARXivar Workflow API
 *
 * OpenAPI spec version: v1
 * Contact: info@abletech.it
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Workflow.Client.SwaggerDateConverter;

namespace IO.Swagger.Workflow.Model
{
    /// <summary>
    /// Multi language value
    /// </summary>
    [DataContract]
        public partial class MultiLanguageValueRm :  IEquatable<MultiLanguageValueRm>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiLanguageValueRm" /> class.
        /// </summary>
        /// <param name="lang">Translation language (required).</param>
        /// <param name="value">Translation value (required).</param>
        public MultiLanguageValueRm(string lang = default(string), string value = default(string))
        {
            // to ensure "lang" is required (not null)
            if (lang == null)
            {
                throw new InvalidDataException("lang is a required property for MultiLanguageValueRm and cannot be null");
            }
            else
            {
                this.Lang = lang;
            }
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for MultiLanguageValueRm and cannot be null");
            }
            else
            {
                this.Value = value;
            }
        }
        
        /// <summary>
        /// Translation language
        /// </summary>
        /// <value>Translation language</value>
        [DataMember(Name="lang", EmitDefaultValue=false)]
        public string Lang { get; set; }

        /// <summary>
        /// Translation value
        /// </summary>
        /// <value>Translation value</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultiLanguageValueRm {\n");
            sb.Append("  Lang: ").Append(Lang).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MultiLanguageValueRm);
        }

        /// <summary>
        /// Returns true if MultiLanguageValueRm instances are equal
        /// </summary>
        /// <param name="input">Instance of MultiLanguageValueRm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MultiLanguageValueRm input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Lang == input.Lang ||
                    (this.Lang != null &&
                    this.Lang.Equals(input.Lang))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Lang != null)
                    hashCode = hashCode * 59 + this.Lang.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

    }
}
