/* 
 * ARXivar Workflow API
 *
 * ARXivar Workflow API
 *
 * OpenAPI spec version: v1
 * Contact: info@abletech.it
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Workflow.Client.SwaggerDateConverter;

namespace IO.Swagger.Workflow.Model
{
    /// <summary>
    /// Process document parameter model
    /// </summary>
    [DataContract]
        public partial class ProcessDocumentParameterRm :  IEquatable<ProcessDocumentParameterRm>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDocumentParameterRm" /> class.
        /// </summary>
        /// <param name="docnumber">Docnumber.</param>
        /// <param name="revision">Index revision.</param>
        /// <param name="kind">Process document kind [0&#x3D;Primary, 1&#x3D;Secondary, 2&#x3D;Attachment].</param>
        /// <param name="filename">Document file name.</param>
        /// <param name="toSend">Indicates if a document can be send.</param>
        public ProcessDocumentParameterRm(int? docnumber = default(int?), int? revision = default(int?), int? kind = default(int?), string filename = default(string), bool? toSend = default(bool?))
        {
            this.Docnumber = docnumber;
            this.Revision = revision;
            this.Kind = kind;
            this.Filename = filename;
            this.ToSend = toSend;
        }
        
        /// <summary>
        /// Docnumber
        /// </summary>
        /// <value>Docnumber</value>
        [DataMember(Name="docnumber", EmitDefaultValue=false)]
        public int? Docnumber { get; set; }

        /// <summary>
        /// Index revision
        /// </summary>
        /// <value>Index revision</value>
        [DataMember(Name="revision", EmitDefaultValue=false)]
        public int? Revision { get; set; }

        /// <summary>
        /// Process document kind [0&#x3D;Primary, 1&#x3D;Secondary, 2&#x3D;Attachment]
        /// </summary>
        /// <value>Process document kind [0&#x3D;Primary, 1&#x3D;Secondary, 2&#x3D;Attachment]</value>
        [DataMember(Name="kind", EmitDefaultValue=false)]
        public int? Kind { get; set; }

        /// <summary>
        /// Document file name
        /// </summary>
        /// <value>Document file name</value>
        [DataMember(Name="filename", EmitDefaultValue=false)]
        public string Filename { get; set; }

        /// <summary>
        /// Indicates if a document can be send
        /// </summary>
        /// <value>Indicates if a document can be send</value>
        [DataMember(Name="toSend", EmitDefaultValue=false)]
        public bool? ToSend { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProcessDocumentParameterRm {\n");
            sb.Append("  Docnumber: ").Append(Docnumber).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  ToSend: ").Append(ToSend).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessDocumentParameterRm);
        }

        /// <summary>
        /// Returns true if ProcessDocumentParameterRm instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessDocumentParameterRm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessDocumentParameterRm input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Docnumber == input.Docnumber ||
                    (this.Docnumber != null &&
                    this.Docnumber.Equals(input.Docnumber))
                ) && 
                (
                    this.Revision == input.Revision ||
                    (this.Revision != null &&
                    this.Revision.Equals(input.Revision))
                ) && 
                (
                    this.Kind == input.Kind ||
                    (this.Kind != null &&
                    this.Kind.Equals(input.Kind))
                ) && 
                (
                    this.Filename == input.Filename ||
                    (this.Filename != null &&
                    this.Filename.Equals(input.Filename))
                ) && 
                (
                    this.ToSend == input.ToSend ||
                    (this.ToSend != null &&
                    this.ToSend.Equals(input.ToSend))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Docnumber != null)
                    hashCode = hashCode * 59 + this.Docnumber.GetHashCode();
                if (this.Revision != null)
                    hashCode = hashCode * 59 + this.Revision.GetHashCode();
                if (this.Kind != null)
                    hashCode = hashCode * 59 + this.Kind.GetHashCode();
                if (this.Filename != null)
                    hashCode = hashCode * 59 + this.Filename.GetHashCode();
                if (this.ToSend != null)
                    hashCode = hashCode * 59 + this.ToSend.GetHashCode();
                return hashCode;
            }
        }

    }
}
